kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "mlbparks-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/tancheeyong/homework.git"
  strategy:
    jenkinsPipelineStrategy:
      env:
         - name: GUID
           value: ${GUID}
         - name: CLUSTER
           value: ${CLUSTER}
         - name: REPO
           value: ${REPO}
      jenkinsfile: |-
        pipeline {
          agent {
            label 'skopeo'
          }
          stages {
            stage('deployInProduction') {
              steps {
                sh "skopeo copy docker://quay.io/cytan/tasks-app:stage docker://quay.io/cytan/tasks-app:prod --src-creds \"cytan:CyRh@645\" --dest-creds \"cytan:CyRh@645\" --src-tls-verify=false --dest-tls-verify=false"
                openshiftDeploy apiURL: 'https://master.rhpds311.openshift.opentlc.com:443', authToken: '_SnmClnYCp3_Zg8cbdhsjneUIz1s3jVq22cdKpJcIww', depCfg: 'tasks', namespace: 'prod-admin', verbose: 'false', waitTime: '', waitUnit: 'sec'
              }
            }
          }
        }
